rem Run this batch file if you want one big text file.
copy Genesis.txt kjv.txt
type Exodus.txt >> kjv.txt
type Lev.txt >> kjv.txt
type Num.txt >> kjv.txt
type Deut.txt >> kjv.txt
type Joshua.txt >> kjv.txt
type Judges.txt >> kjv.txt
type Ruth.txt >> kjv.txt
type 1Sam.txt >> kjv.txt
type 2Sam.txt >> kjv.txt
type 1Kings.txt >> kjv.txt
type 2Kings.txt >> kjv.txt
type 1Chron.txt >> kjv.txt
type 2Chron.txt >> kjv.txt
type Ezra.txt >> kjv.txt
type Nehemiah.txt >> kjv.txt
type Esther.txt >> kjv.txt
type Job.txt >> kjv.txt
type Psalms.txt >> kjv.txt
type Proverbs.txt >> kjv.txt
type Eccl.txt >> kjv.txt
type Song.txt >> kjv.txt
type Isaiah.txt >> kjv.txt
type Jeremiah.txt >> kjv.txt
type Lament.txt >> kjv.txt
type Ezekiel.txt >> kjv.txt
type Daniel.txt >> kjv.txt
type Hosea.txt >> kjv.txt
type Joel.txt >> kjv.txt
type Amos.txt >> kjv.txt
type Obadiah.txt >> kjv.txt
type Jonah.txt >> kjv.txt
type Micah.txt >> kjv.txt
type Nahum.txt >> kjv.txt
type Habakkuk.txt >> kjv.txt
type Zeph.txt >> kjv.txt
type Haggai.txt >> kjv.txt
type Zech.txt >> kjv.txt
type Malachi.txt >> kjv.txt
type Matthew.txt >> kjv.txt
type Mark.txt >> kjv.txt
type Luke.txt >> kjv.txt
type John.txt >> kjv.txt
type Acts.txt >> kjv.txt
type Romans.txt >> kjv.txt
type 1Cor.txt >> kjv.txt
type 2Cor.txt >> kjv.txt
type Gal.txt >> kjv.txt
type Eph.txt >> kjv.txt
type Philip.txt >> kjv.txt
type Col.txt >> kjv.txt
type 1Thes.txt >> kjv.txt
type 2Thes.txt >> kjv.txt
type 1Tim.txt >> kjv.txt
type 2Tim.txt >> kjv.txt
type Titus.txt >> kjv.txt
type Philemon.txt >> kjv.txt
type Hebrews.txt >> kjv.txt
type James.txt >> kjv.txt
type 1Peter.txt >> kjv.txt
type 2Peter.txt >> kjv.txt
type 1John.txt >> kjv.txt
type 2John.txt >> kjv.txt
type 3John.txt >> kjv.txt
type Jude.txt >> kjv.txt
type Rev.txt >> kjv.txt
copy Tobit.txt apoc.txt
type Judith.txt >> apoc.txt
type GkEsther.txt >> apoc.txt
type Wisdom.txt >> apoc.txt
type Sirach.txt >> apoc.txt
type Baruch.txt >> apoc.txt
type Let.txt >> apoc.txt
type Azar.txt >> apoc.txt
type Susanna.txt >> apoc.txt
type Bel.txt >> apoc.txt
type 1Mac.txt >> apoc.txt
type 2Mac.txt >> apoc.txt
type 1Esdras.txt >> apoc.txt
type 2Esdras.txt >> apoc.txt
type Man.txt >> apoc.txt




